package view;
import javax.swing.*;
import java.awt.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame implements ViewInterface{
    private ViewInterface.ViewListener listener;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setSize(600,400);
        this.setLocationRelativeTo(null);
    }

    @Override
    public void displayResult(String algo, long result) {
        lblResult.setText(algo + ": " + result);
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }


    @Override
    public void displayError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error:", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void setAlgorithmsList(String[] algos) {
        for (String a : algos) combo.addItem(a);
    }

    @Override
    public void setGeneratorsList(String[] generators)
    {
        for (String generator : generators) {
            generatorsCombo.addItem(generator);
        }
    }


    @Override
    public void setListener(ViewListener listener) {
        this.listener = listener;
    }

    @Override
    public void showView() {
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        lblSelectedFile = new javax.swing.JLabel();
        btnSelectFile = new javax.swing.JButton();
        btnProcessVideo = new javax.swing.JButton();
        generatorsCombo = new javax.swing.JComboBox<>();
        lblGeneratorSelection = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combo.setName("combo"); // NOI18N
        generatorsCombo.setName("generatorsCombo");

        jLabel1.setText("Select algorithm");
        lblGeneratorSelection.setText("Select generator");

        btn.setText("Generate");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        lblResult.setText("Result: ---");

        lblSelectedFile.setText("Current file: Default");

        btnSelectFile.setText("Select file");
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });

        btnProcessVideo.setText("Process video");
        btnProcessVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessVideoActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblGeneratorSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblSelectedFile))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(generatorsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                                .addComponent(btnSelectFile))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnProcessVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lblResult)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(lblGeneratorSelection)
                                        .addComponent(lblSelectedFile))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(generatorsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSelectFile))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn)
                                        .addComponent(btnProcessVideo))
                                .addGap(30, 30, 30)
                                .addComponent(lblResult)
                                .addContainerGap(50, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {                                    
        if (listener != null) {
            String algorithm = (String) combo.getSelectedItem();
            String generator = (String) generatorsCombo.getSelectedItem();
            boolean processingVideo = false;
            listener.onGenerateClicked(algorithm,generator, processingVideo);
        }

    }

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed
    JFileChooser fileChooser = new JFileChooser();
        
        // Ustawiamy folder startowy na folder projektu (kropka)
        fileChooser.setCurrentDirectory(new java.io.File("."));
        
        // Otwieramy okno
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();
            
            // 1. Aktualizujemy napis w GUI
            lblSelectedFile.setText("File: " + selectedFile.getName());
            
            // 2. Powiadamiamy kontroler (żeby zmienił plik w logice)
            if (listener != null) {
                listener.onFileSelected(selectedFile);
            }
        }
    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void btnProcessVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessVideoActionPerformed
        if (listener != null) {
            String algorithm = (String) combo.getSelectedItem();
            String generator = (String) generatorsCombo.getSelectedItem();
            boolean processingVideo = true; 
            listener.onGenerateClicked(algorithm,generator, processingVideo);
        }
    }//GEN-LAST:event_btnProcessVideoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | InstantiationException |
                 IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnProcessVideo;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> generatorsCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSelectedFile;
    private javax.swing.JLabel lblGeneratorSelection;
    // End of variables declaration//GEN-END:variables
}
